### ISSUE TITLE
How to set up it on Eclipse

### ISSUE THREAD

**Issue by llUnknownl** [PaceCodes/Jigsaw#3]
I'm a bit late, but I wish you could help me to set the client up in Eclipse IDE

**Comment by PaceCodes** [comment]
These are the steps:

1. Download and setup mcp (modcoderpack.com) workspace of your desired version.
2. Setup that mcp workspace in your eclipse and run it.
3. At the place of `src/minecraft/` replace the existing files with the ones you have downloaded [Make sure that the version of mcp and version of jigsaw, are the same minecraft versions]
4. Import all the libraries / add them. 
5. Run it again.

To setup mcp workspace there are plenty of youtube videos avaliable. [TIP: This is a bad hacked client to skid from. There are many other better ones]

**Comment by llUnknownl** [comment]
Got it, Thanks.
I know it's hard to skid from it but I'm interested on it's hacker detector.

**Comment by PaceCodes** [comment]
A suggestion :
Don't just skid blatantly but rather try to understand and learn from it. Have a nice time learning java. 👍

**Comment by llUnknownl** [comment]
That's another thing I want to do. I tried to make a forge mod with my own
detecting system but I'm a bit lost at programming in Minecraft, and I know
it's not the same forge and normal version like jigsaw is, but I think I
can learn a lot from it. (I already know some Java, I just don't know how
to implement things in MC)

But my original idea is to make a forge mod to detect hacks. (1.8.8 or
1.8.9, whatever)
